# Railway Production Configuration
# This file helps Railway understand how to build and run the bot

[build]
builder = "NIXPACKS"

[build.env]
NODE_VERSION = "20"

[deploy]
startCommand = "node bot.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 2

[env]
# Note: Set these in Railway dashboard, not here
# DISCORD_TOKEN = "required"
# OPENAI_API_KEY = "required"
# MONGO_URI = "required"
# CLIENT_ID = "required"
# GUILD_ID = "optional"
# PORT will be set automatically by Railway
